### ISSUE TITLE
Создание репозитория

### ISSUE THREAD

**Issue by Bizhev** [open-dev-team/music_backend#1]
@xzlink, используем самую последнюю версию, DB, PHP etc.
1. Нужно залить сюда готовый проект на PHP Laravel последней версии.
1. Завязать его с Maria DB (локально) использую инструменты Laravel.
1. Затем нужно будет создать в БД таблицу **Users** с полями: 

- login
- password
- fio
- id

**Comment by xzlink** [comment]
✔️
